import React,{useEffect} from 'react';
import {useDashboardTabs,useDataApp} from '../../data-app-public.jsx';
import {useAnalyticsLive} from '../shared/analytics-live.tsx';
import {moveDate,today} from '../shared/analytics-contract.ts';
import {copy} from '../shared/analytics-copy.js';
import {Glyph,localTime} from '../shared/analytics-ui.jsx';
import {OwnerView} from './OwnerView.jsx';
import {OperationsView} from './OperationsView.jsx';
import './masaflow-analytics.css';
export function DashboardContent(){
 const live=useAnalyticsLive(),{queries}=useDataApp();const lang=live.scope.lang,t=copy[lang];const {activeTabId}=useDashboardTabs([{id:'operations',label:t.operations,previousLabels:['Operations','Operación']},{id:'owner',label:t.owner,aliases:['sales'],previousLabels:['Sales','Ventas']}]);
 useEffect(()=>{if(activeTabId==='operations'||activeTabId==='owner')live.changeScope({tab:activeTabId});},[activeTabId]);
 const view=activeTabId==='owner'?'owner':'operations';const dto=live.dto;const selectLanguage=next=>{live.changeScope({lang:next});window.MasaFlowI18n?.setLocale(next);};const pending=dto&&(dto.scope.date!==live.scope.date||dto.scope.period!==live.scope.period||dto.scope.lang!==lang);
 return <article className="mf-analytics" data-dashboard-layout="full-width"><nav className="mf-rail" aria-label="MasaFlow"><a className="mf-brand" href="/businessDashbord.html" aria-label="MasaFlow">M</a>{[['orders','ticket','/businessDashbord.html'],['register','plus','/MenuUI.html'],['kitchen','fire','/businessDashbord.html'],['metrics','chart','/analytics/'],['menu','menu','/MenuManagment.html'],['history','clock','/history.html']].map(([label,icon,href])=><a key={label} href={href} aria-current={label==='metrics'?'page':undefined}><Glyph name={icon}/><span>{t[label]}</span></a>)}</nav><div className="mf-page"><div className="mf-mobile-brand"><a href="/businessDashbord.html"><span>M</span>MasaFlow</a></div><header className="mf-intro"><div><h1 data-editable-id={'masa-'+view+'-heading'}>{view==='owner'?t.ownerTitle:t.operationTitle}</h1><p>{view==='owner'?t.ownerSub:t.operationSub}</p></div><div className="mf-intro-actions"><span className="mf-local-badge">{t.live}</span><div className="mf-languages" aria-label={t.language}>{['es','en'].map(locale=><button key={locale} type="button" onClick={()=>selectLanguage(locale)} aria-pressed={lang===locale}>{locale.toUpperCase()}</button>)}</div></div></header>
 <div className="mf-controls"><div className="mf-sales-controls">{view==='owner'&&<><div className="mf-periods">{['day','week','month','year'].map(period=><button key={period} aria-pressed={live.scope.period===period} onClick={()=>live.changeScope({period})}>{t[period]}</button>)}</div><div className="mf-date-controls"><button aria-label={t.previous} onClick={()=>live.changeScope({date:moveDate(live.scope,-1)})}>‹</button><input type="date" aria-label={t.date} value={live.scope.date} onChange={event=>live.changeScope({date:event.target.value||today()})}/><button aria-label={t.next} onClick={()=>live.changeScope({date:moveDate(live.scope,1)})}>›</button></div></>}<span className="mf-timezone">{dto?.timezone||'America/Mexico_City'}</span></div><div className="mf-sync"><span className={'mf-status-dot '+(live.connected?'':'is-offline')}/><span>{live.connected?t.sync:t.offline}{dto?' '+localTime(dto.observedAt,dto,lang):''}</span><button className="mf-icon-button" onClick={live.refresh} aria-label={t.refresh} title={t.refresh}><Glyph name="refresh"/></button></div></div>
 {live.error&&<div className="mf-connection-alert" role="status">{live.connected?live.error:t.offline}<button onClick={live.refresh}>{t.retry}</button></div>}{pending&&<p className="mf-loading" role="status">{t.newScope} {dto.scope.date} · {t[dto.scope.period]}</p>}{!dto?<div className="mf-first-load" role="status"><Glyph name="database" size={34}/><h2>{t.initial}</h2><button className="mf-button" onClick={live.refresh}>{t.retry}</button></div>:<>{view==='owner'?<OwnerView dto={dto} t={t} lang={lang} queries={queries}/>:<OperationsView dto={dto} t={t} lang={lang} queries={queries}/>}<footer className="mf-footer"><span>{t.footer} · {dto.currency} · {dto.timezone}</span>{dto.quality.excludedReceipts>0&&<span className="mf-quality">{dto.quality.excludedReceipts} {t.quality}</span>}{dto.quality.invalidAudits>0&&<span className="mf-quality">{dto.quality.invalidAudits} {lang==='es'?'auditorías inconsistentes excluidas':'inconsistent audits excluded'}</span>}{dto.quality.invalidCompletionTimes>0&&<span className="mf-quality">{dto.quality.invalidCompletionTimes} {lang==='es'?'tiempos de entrega inválidos excluidos':'invalid completion times excluded'}</span>}</footer></>}</div></article>;
}
