import React from 'react';
import {Card,Metric,Glyph,money,minutes} from '../shared/analytics-ui.jsx';
export function OperationsView({dto,t,lang,queries}){
 const o=dto.operations,shift=o.currentShift,audit=o.latestAudit;const format=(value,currency=dto.currency)=>money(value,currency,lang);const age=order=>Math.max(0,Math.floor((Date.parse(dto.observedAt)-Date.parse(order.paidAt))/60000));
 return <><div className="mf-kpis mf-ops-kpis"><Metric id="kitchen-count" queryId="operations_summary" title={t.count} value={o.activeCount} hint={t.countHint} icon="kitchen" rows={queries.operations_summary.rows}/><Metric id="oldest-ticket" queryId="operations_summary" title={t.oldest} value={minutes(o.oldestAgeMinutes,t)} hint={t.oldestHint} icon="clock" rows={queries.operations_summary.rows}/><Metric id="pickup-time" queryId="operations_summary" title={t.pickup} value={minutes(o.medianPickupMinutes,t)} hint={`${t.median} · ${o.completedSampleCount} ${t.completed}`} icon="clock" rows={queries.operations_summary.rows}/><Metric id="expected-cash" queryId="drawer_reconciliation" title={t.expected} value={shift?format(shift.expectedCents,shift.currency):'—'} hint={t.expectedHint} icon="cash" rows={queries.drawer_reconciliation.rows}/></div>
 <div className="mf-two-columns mf-operations-grid"><Card id="active-tickets" queryId="active_queue" rows={o.activeOrders} title={t.queue} className="mf-queue"><p className="mf-muted">{t.queueHint}</p><div className="mf-stages" data-reviewed-rows>{['pending','preparing','ready'].map((stage,index)=><div key={stage}><Glyph name={['ticket','fire','ready'][index]}/><span>{t[stage]}</span><strong>{o.counts[stage]}</strong></div>)}</div>{o.activeOrders.length?<div className="mf-table-scroll" role="region" tabIndex={0} aria-label={t.queue} data-reviewed-rows><table className="mf-table mf-queue-table"><thead><tr><th>{t.ticket}</th><th>{t.stage}</th><th>{t.age}</th><th>{t.kitchen}</th></tr></thead><tbody>{o.activeOrders.map(row=><tr key={row.id}><td><strong>{row.ticket}</strong></td><td><span className={'mf-badge '+row.status}>{t[row.status]||row.status}</span></td><td>{age(row)} {t.min}</td><td><a href={'/businessDashbord.html?order='+encodeURIComponent(row.id)} aria-label={t.goto+' '+row.ticket}>{t.goto} →</a></td></tr>)}</tbody></table></div>:<p className="mf-empty">{t.noQueue}</p>}</Card>
 <div className="mf-stacked"><Card id="shift-drawer" queryId="drawer_reconciliation" rows={queries.drawer_reconciliation.rows} title={t.shift}>{shift?<><dl className="mf-reconciliation" data-reviewed-rows><div><dt>{t.float}</dt><dd>{format(shift.floatCents,shift.currency)}</dd></div><div><dt>{t.receipts}</dt><dd>{format(shift.receiptsCents,shift.currency)}</dd></div><div><dt>{t.drops}</dt><dd>{format(shift.dropsCents,shift.currency)}</dd></div><div className="mf-reconciliation-total"><dt>{t.expected}</dt><dd>{format(shift.expectedCents,shift.currency)}</dd></div></dl><p className="mf-count-pending"><Glyph name="clock"/>{t.counting}</p></>:<p className="mf-empty">{t.noShift}</p>}<a className="mf-button mf-outline" href="/history.html"><Glyph name="cash"/>{t.ledger}</a></Card>
 <Card id="closed-audit" queryId="drawer_audit" rows={queries.drawer_audit.rows} title={t.audit}>{audit?<div data-reviewed-rows><time className="mf-muted">{new Intl.DateTimeFormat(lang==='es'?'es-MX':'en-US',{timeZone:dto.timezone,dateStyle:'medium'}).format(new Date(audit.closedAt))}</time><div className="mf-audit-value"><strong className={audit.varianceCents<0?'mf-negative':audit.varianceCents>0?'mf-positive':''}>{audit.varianceCents>0?'+':''}{format(audit.varianceCents,audit.currency)}</strong><span className={'mf-badge '+(audit.varianceCents<0?'short':'ready')}>{audit.varianceCents<0?t.short:audit.varianceCents>0?t.over:t.balanced}</span></div><div className="mf-audit-counts"><div><span>{t.expected}</span><b>{format(audit.expectedCents,audit.currency)}</b></div><div><span>{t.actual}</span><b>{format(audit.actualCents,audit.currency)}</b></div></div><p className="mf-muted">{t.variance}</p></div>:<p className="mf-empty">{t.noAudit}</p>}</Card></div></div>
 <div className="mf-two-columns mf-bottom-cards"><Card id="drawer-exceptions" queryId="drawer_exceptions" rows={o.drawerExceptions} title={o.drawerExceptions.length?o.drawerExceptions.length+' '+t.exceptions:t.noExceptions} className={o.drawerExceptions.length?'mf-exception':''}><div className="mf-compact-content"><Glyph name={o.drawerExceptions.length?'warning':'ready'}/><p className="mf-muted">{o.drawerExceptions.length?t.exceptionsHint:t.noExceptions}</p><a href="/history.html" aria-label={t.ledger}>→</a></div></Card><Card id="data-definitions" queryId="operations_summary" rows={queries.operations_summary.rows} title={t.definition}><div className="mf-compact-content"><Glyph name="database"/><p className="mf-muted">{t.definitionHint}</p></div></Card></div></>;
}
