import React,{useEffect,useRef,useState} from 'react';
import {EvidenceChart,barChartSpec} from '../../data-app-public.jsx';
import {useAnalyticsLive} from '../shared/analytics-live.tsx';
import {Card,Metric,Glyph,money,minutes,localTime} from '../shared/analytics-ui.jsx';
function SalesSummary({dto,t,lang}){
 const [result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const generation=useRef(0);
 const {loading,connected}=useAnalyticsLive();
 useEffect(()=>{generation.current++;setResult(null);setError('');setBusy(false);},[dto.revision,dto.scope.period,dto.scope.date,lang]);
 async function generate(){const id=++generation.current;setBusy(true);setError('');try{const response=await fetch('/api/analytics/summary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scope:dto.scope,locale:lang,revision:dto.revision})});const body=await response.json();if(id!==generation.current)return;if(!response.ok)throw new Error(response.status===409?t.summaryStale:body.error||t.summaryError);if(!body.summary||typeof body.summary.headline!=='string'||!Array.isArray(body.summary.findings)||body.revision!==dto.revision)throw new Error(t.summaryError);setResult(body);}catch(failure){if(id===generation.current)setError(failure.message);}finally{if(id===generation.current)setBusy(false);}}
 const fmt=finding=>['MXN','USD','cents'].includes(finding.unit)?money(finding.value,finding.unit==='cents'?dto.currency:finding.unit,lang):finding.unit==='minutes'?minutes(finding.value,t):String(finding.value??'—');
 return <Card id="sales-summary-ai" queryId="sales_summary" rows={[{receiptsCents:dto.sales.receiptsCents,subtotalCents:dto.sales.subtotalCents,taxCents:dto.sales.taxCents,ticketCount:dto.sales.ticketCount,averageCents:dto.sales.averageCents}]} title={t.summary} className="mf-summary"><p className="mf-muted">{t.summaryHint}</p><button className="mf-button mf-primary" onClick={generate} disabled={!dto.summaryAvailable||busy||loading||!connected}>{busy?t.generating:t.generate}</button><div className="mf-summary-body" aria-live="polite">{error?<p role="alert">{error}</p>:result?<><strong>{result.summary.headline}</strong>{result.summary.findings.map((finding,i)=><p key={i}><b>{fmt(finding)}</b> — {finding.commentary}</p>)}{result.summary.caveats?.map((c,i)=><small key={i}>{c}</small>)}</>:<><Glyph name="ticket" size={32}/><p>{dto.summaryAvailable?t.summaryEmpty:t.unavailable}</p></>}</div></Card>;
}
export function OwnerView({dto,t,lang,queries}){
 const s=dto.sales,format=value=>money(value,dto.currency,lang),metricRows=queries.sales_summary.rows;
 const taxHint=dto.taxConfigured ? (lang==='es'?'Impuesto configurado: ':'Configured tax: ')+(dto.taxBasisPoints/100)+'%' : t.taxHint;
 return <><div className="mf-kpis mf-sales-kpis"><Metric id="cash-receipts" queryId="sales_summary" title={t.receipts} value={format(s.receiptsCents)} hint={t.totalHint} dark rows={metricRows}/><Metric id="sales-subtotal" queryId="sales_summary" title={t.subtotal} value={format(s.subtotalCents)} hint={taxHint} rows={metricRows}/><Metric id="paid-tickets" queryId="sales_summary" title={t.tickets} value={s.ticketCount} hint={t.ticketsHint} rows={metricRows}/><Metric id="average-ticket" queryId="sales_summary" title={t.average} value={format(s.averageCents)} hint={t.avgHint} rows={metricRows}/></div>
 <div className="mf-two-columns mf-sales-charts"><EvidenceChart id="receipt-trend" queryId="sales_buckets" title={t.trend} variant="card" padding="spacious" className="mf-card" spec={barChartSpec({presentation:'plot',category:'label',value:'amount',domain:[0,'auto'],axes:{category:true,value:true},style:{color:'#ff5100',radius:5},format:{style:'currency',currency:dto.currency,maximumFractionDigits:2}})} rows={queries.sales_buckets.rows} sourceRows={queries.sales_buckets.rows} height={270}><p className="mf-muted">{t.trendHint} {dto.timezone}</p><details className="mf-data-table"><summary>{t.table}</summary><table><thead><tr><th>{t.time}</th><th>{t.receipts}</th><th>{t.tickets}</th></tr></thead><tbody>{s.buckets.map(row=><tr key={row.date+row.label}><td>{row.label}</td><td>{format(row.receiptsCents)}</td><td>{row.ticketCount}</td></tr>)}</tbody></table></details></EvidenceChart>
 <EvidenceChart id="top-dishes" queryId="menu_rank" title={t.top} variant="card" padding="spacious" className="mf-card" spec={barChartSpec({presentation:'rankedList',category:'name',value:'quantity',style:{color:'#ff5100',thickness:10,radius:6,fontSize:14,gap:17},labels:{position:'above'},domain:[0,'auto'],expandable:true,visibleRows:5,format:{maximumFractionDigits:0}})} rows={s.topItems} sourceRows={s.topItems} height={270}><p className="mf-muted">{t.topHint}</p><details className="mf-data-table"><summary>{t.table}</summary><table><thead><tr><th>{t.menu}</th><th>{t.unit}</th></tr></thead><tbody>{s.topItems.map(row=><tr key={row.menuItemId||row.name}><td>{row.name}</td><td>{row.quantity}</td></tr>)}</tbody></table></details></EvidenceChart></div>
 <div className="mf-two-columns"><Card id="recent-tickets" queryId="receipts" rows={s.recentReceipts} title={t.recent}><div className="mf-card-intro"><p className="mf-muted">{t.recentHint}</p><a href="/history.html">{t.ledger} →</a></div>{s.recentReceipts.length?<div className="mf-table-scroll" data-reviewed-rows><table className="mf-table"><thead><tr><th>{t.ticket}</th><th>{t.total}</th><th>{t.status}</th><th>{t.time}</th></tr></thead><tbody>{s.recentReceipts.slice(0,6).map(row=><tr key={row.orderId}><td><strong>{row.ticket}</strong></td><td>{format(row.totalCents)}</td><td><span className="mf-badge ready">{t.paid}</span></td><td>{localTime(row.paidAt,dto,lang)}</td></tr>)}</tbody></table></div>:<p className="mf-empty">{t.empty}</p>}</Card><SalesSummary dto={dto} t={t} lang={lang}/></div>
 {dto.currencyTotals?.filter(row=>row.currency!==dto.currency&&row.ticketCount>0).map(row=><p className="mf-legacy" key={row.currency}>{t.legacy}: <strong>{money(row.receiptsCents,row.currency,lang)}</strong> · {row.ticketCount} {t.tickets.toLowerCase()}</p>)}<p className="mf-footnote">{t.caveat}</p></>;
}
