import type { AcademyStep } from "./types";

export const ACADEMY_MODULES = [
  {
    id: "module1_golden_path" as const,
    number: 1,
    title: "El Flujo Perfecto",
    subtitle: "Aceptar → Cocinar → Entregar y Cobrar",
    description: "Aprende el camino de oro de cada comanda: desde que entra a cocina hasta que cobras en efectivo.",
  },
  {
    id: "module2_picky_eater" as const,
    number: 2,
    title: "El Cliente Exigente",
    subtitle: "Restricciones y Alergias Obligatorias",
    description: "Reconoce modificadores críticos como 'SIN QUESO'. La cocina exige confirmación táctil antes de preparar.",
  },
  {
    id: "module3_mistakes_noshow" as const,
    number: 3,
    title: "Errores y Fantasmas",
    subtitle: "Ventana de Deshacer (5s) y Pedidos Abandonados",
    description: "Corrige errores de cobro antes de que afecten la caja y anula pedidos de comensales que nunca llegaron.",
  },
  {
    id: "module4_panic_86" as const,
    number: 4,
    title: "Pánico y Agotados",
    subtitle: "86 de Platillos e Interrupción de Pedidos Web",
    description: "Controla horas pico: apaga platillos agotados en la app y activa el botón de pánico cuando la cocina se satura.",
  },
  {
    id: "module5_revenue_closeout" as const,
    number: 5,
    title: "Ganancias y Cierre",
    subtitle: "Auditoría de Efectivo y Arqueo Ciego de Caja",
    description: "Revisa las ventas reales acumuladas en tu práctica y realiza el corte de caja ciego al centavo.",
  },
];

export const CURRICULUM_STEPS: AcademyStep[] = [
  // --- MÓDULO 1: EL FLUJO PERFECTO ---
  {
    id: "m1_step1_accept",
    moduleId: "module1_golden_path",
    moduleNumber: 1,
    moduleTitle: "El Flujo Perfecto",
    stepNumber: 1,
    totalSteps: 5,
    target: "accept-demo-order",
    action: "accept",
    title: "1. Aceptar Comanda en Cocina",
    instruction: "Toca «Aceptar y empezar a cocinar» para tomar la comanda.",
    backendConsequence: "Mueve el ticket a 'Cocinando' y envía una notificación instantánea al teléfono del cliente indicando que su comida ya está en el comal.",
    valueWhy: "Evita que el comensal pregunte en el mostrador y sincroniza los tiempos de cocción de todo el equipo.",
    targetLane: "review",
  },
  {
    id: "m1_step2_ready",
    moduleId: "module1_golden_path",
    moduleNumber: 1,
    moduleTitle: "El Flujo Perfecto",
    stepNumber: 2,
    totalSteps: 5,
    target: "mark-demo-ready",
    action: "ready",
    title: "2. Marcar Comanda Lista",
    instruction: "Toca 'Lista'. Esto envía una notificación al teléfono del cliente para que se acerque al mostrador.",
    backendConsequence: "Pasa la orden a 'Lista para recoger' y hace sonar la campana en el teléfono del cliente para que se acerque al mostrador.",
    valueWhy: "Garantiza que la comida se entregue bien caliente y recién servida sin tener que gritar nombres.",
    targetLane: "cooking",
  },
  {
    id: "m1_step3_pay_open",
    moduleId: "module1_golden_path",
    moduleNumber: 1,
    moduleTitle: "El Flujo Perfecto",
    stepNumber: 3,
    totalSteps: 5,
    target: "pay-demo-order",
    action: "pay",
    title: "3. Cobrar al Entregar",
    instruction: "El cliente llega a la barra. Toca «Cobrar al entregar».",
    backendConsequence: "Abre la calculadora táctil de cobro con el total exacto del pedido ($185.00 MXN) y los billetes preconfigurados.",
    valueWhy: "Cobrar siempre al entregar elimina el riesgo de pedidos no cobrados.",
    targetLane: "ready",
  },
  {
    id: "m1_step4_tender_200",
    moduleId: "module1_golden_path",
    moduleNumber: 1,
    moduleTitle: "El Flujo Perfecto",
    stepNumber: 4,
    totalSteps: 5,
    target: "tender-200",
    action: "cash-preset",
    title: "4. Seleccionar Billete Recibido",
    instruction: "El cliente te da un billete de $200. Toca el botón «$200.00».",
    backendConsequence: "El sistema toma $200.00 recibidos y calcula en pantalla el cambio matemático exacto: $15.00 MXN.",
    valueWhy: "No calcules en tu mente. Toca el billete recibido y el sistema te dirá exactamente cuánto cambio dar para evitar descuadres.",
  },
  {
    id: "m1_step5_confirm_pay",
    moduleId: "module1_golden_path",
    moduleNumber: 1,
    moduleTitle: "El Flujo Perfecto",
    stepNumber: 5,
    totalSteps: 5,
    target: "confirm-demo-payment",
    action: "confirm",
    title: "5. Confirmar y Finalizar Cobro",
    instruction: "Entrega los $15.00 de cambio y toca «Confirmar cobro de $200.00».",
    backendConsequence: "Asienta el pago en la caja, transfiere el pedido al historial de completados y suma $185.00 a las ventas del turno.",
    valueWhy: "Cierra la orden de manera inmutable; el cliente recibe su recibo digital y la fila avanza con rapidez.",
  },

  // --- MÓDULO 2: EL CLIENTE EXIGENTE ---
  {
    id: "m2_step1_accept",
    moduleId: "module2_picky_eater",
    moduleNumber: 2,
    moduleTitle: "El Cliente Exigente",
    stepNumber: 1,
    totalSteps: 6,
    target: "accept-demo-order",
    action: "accept",
    title: "1. Aceptar Pedido con Modificaciones",
    instruction: "Llegó un pedido con preferencias estrictas. Toca «Aceptar y empezar a cocinar».",
    backendConsequence: "Mueve el ticket a cocina y alerta al personal sobre peticiones especiales.",
    valueWhy: "Permite que la cocina revise las especificaciones antes de poner la masa al comal.",
    targetLane: "review",
  },
  {
    id: "m2_step2_ack_badge",
    moduleId: "module2_picky_eater",
    moduleNumber: 2,
    moduleTitle: "El Cliente Exigente",
    stepNumber: 2,
    totalSteps: 6,
    target: "acknowledge-restriction",
    action: "acknowledge",
    title: "2. Confirmar Alergia / Restricción (Obligatorio)",
    instruction: "¡ALERTA! El cliente pidió omisión estricta (SIN CEBOLLA / SIN QUESO). Toca la insignia roja para confirmar que la cocina leyó la omisión.",
    backendConsequence: "Libera el bloqueo de seguridad del ticket. La cocina no podrá despachar este pedido sin antes certificar que leyeron la omisión.",
    valueWhy: "Protección absoluta contra alergias alimentarias y devoluciones por ingredientes no deseados.",
    targetLane: "cooking",
  },
  {
    id: "m2_step3_ready",
    moduleId: "module2_picky_eater",
    moduleNumber: 2,
    moduleTitle: "El Cliente Exigente",
    stepNumber: 3,
    totalSteps: 6,
    target: "mark-demo-ready",
    action: "ready",
    title: "3. Marcar Comanda Lista",
    instruction: "Restricción cumplida. Toca «Marcar lista para recoger».",
    backendConsequence: "Mueve el ticket a entrega y avisa al cliente que su orden personalizada está lista.",
    valueWhy: "La orden se entrega con la certeza de que no lleva queso.",
    targetLane: "cooking",
  },
  {
    id: "m2_step4_pay_open",
    moduleId: "module2_picky_eater",
    moduleNumber: 2,
    moduleTitle: "El Cliente Exigente",
    stepNumber: 4,
    totalSteps: 6,
    target: "pay-demo-order",
    action: "pay",
    title: "4. Cobrar Pedido Especial",
    instruction: "Toca «Cobrar al entregar» para recibir el pago.",
    backendConsequence: "Abre la ventana de caja para recibir el dinero.",
    valueWhy: "Mantiene la velocidad habitual de despacho.",
    targetLane: "ready",
  },
  {
    id: "m2_step5_tender_200",
    moduleId: "module2_picky_eater",
    moduleNumber: 2,
    moduleTitle: "El Cliente Exigente",
    stepNumber: 5,
    totalSteps: 6,
    target: "tender-200",
    action: "cash-preset",
    title: "5. Seleccionar Billete de $200",
    instruction: "El cliente paga con $200. Toca el botón «$200.00».",
    backendConsequence: "Calcula $15.00 de cambio exacto.",
    valueWhy: "Seguridad y velocidad en el arqueo.",
  },
  {
    id: "m2_step6_confirm",
    moduleId: "module2_picky_eater",
    moduleNumber: 2,
    moduleTitle: "El Cliente Exigente",
    stepNumber: 6,
    totalSteps: 6,
    target: "confirm-demo-payment",
    action: "confirm",
    title: "6. Confirmar Cobro del Pedido Especial",
    instruction: "Toca «Confirmar cobro de $200.00».",
    backendConsequence: "Archiva el segundo pedido y acumula $370.00 MXN en el total del turno.",
    valueWhy: "Registro contable exacto sin contaminar datos reales.",
  },

  // --- MÓDULO 3: ERRORES Y FANTASMAS ---
  {
    id: "m3_step1_pay_mistake",
    moduleId: "module3_mistakes_noshow",
    moduleNumber: 3,
    moduleTitle: "Errores y Fantasmas",
    stepNumber: 1,
    totalSteps: 9,
    target: "pay-demo-order",
    action: "pay",
    title: "1. Cobro con Error de Monto",
    instruction: "Un cliente te entrega un billete de $500. Toca «Cobrar al entregar».",
    backendConsequence: "Abre la calculadora de cobro.",
    valueWhy: "Simula el escenario más común de error cuando hay prisa en el mostrador.",
    targetLane: "ready",
  },
  {
    id: "m3_step2_wrong_tender",
    moduleId: "module3_mistakes_noshow",
    moduleNumber: 3,
    moduleTitle: "Errores y Fantasmas",
    stepNumber: 2,
    totalSteps: 9,
    target: "tender-200",
    action: "cash-preset",
    title: "2. Error de Dedo: Tocar $200 por Accidente",
    instruction: "Por distracción, toca el billete de «$200.00» (¡cuando te dieron $500!).",
    backendConsequence: "El sistema prepara el cobro asumiendo que recibiste $200 en lugar de $500.",
    valueWhy: "Demuestra la red de seguridad del sistema ante equivocaciones del cajero.",
  },
  {
    id: "m3_step3_confirm_mistake",
    moduleId: "module3_mistakes_noshow",
    moduleNumber: 3,
    moduleTitle: "Errores y Fantasmas",
    stepNumber: 3,
    totalSteps: 9,
    target: "confirm-demo-payment",
    action: "confirm",
    title: "3. Confirmar Cobro Erróneo",
    instruction: "Toca «Confirmar cobro de $200.00».",
    backendConsequence: "Dispara la alarma sonora y activa la ventana de gracia de 5 segundos antes de asentar el cobro definitivo.",
    valueWhy: "El sistema nunca asienta cobros instantáneamente sin dar una ventana de rectificación.",
  },
  {
    id: "m3_step4_undo",
    moduleId: "module3_mistakes_noshow",
    moduleNumber: 3,
    moduleTitle: "Errores y Fantasmas",
    stepNumber: 4,
    totalSteps: 9,
    target: "undo-demo-payment",
    action: "undo",
    title: "4. Salvar la Caja: Tocar «Deshacer» en 5s",
    instruction: "¡Rápido! Toca el botón rojo «Deshacer» antes de que la cuenta llegue a cero.",
    backendConsequence: "Cancela la transacción en curso, detiene el envío al servidor y restaura el pedido a la fila para cobrarlo correctamente.",
    valueWhy: "Evita descuadres de caja y reclamos de cambio sin necesitar la clave del supervisor.",
    targetLane: "ready",
  },
  {
    id: "m3_step5_pay_corrected",
    moduleId: "module3_mistakes_noshow",
    moduleNumber: 3,
    moduleTitle: "Errores y Fantasmas",
    stepNumber: 5,
    totalSteps: 9,
    target: "pay-demo-order",
    action: "pay",
    title: "5. Cobrar con el Monto Correcto",
    instruction: "¡Salvado! Ahora toca de nuevo «Cobrar al entregar».",
    backendConsequence: "Reabre la ventana de cobro limpia para ingresar el billete correcto.",
    valueWhy: "Permite corregir el error en menos de tres segundos.",
    targetLane: "ready",
  },
  {
    id: "m3_step6_tender_500",
    moduleId: "module3_mistakes_noshow",
    moduleNumber: 3,
    moduleTitle: "Errores y Fantasmas",
    stepNumber: 6,
    totalSteps: 9,
    target: "tender-500",
    action: "cash-preset",
    title: "6. Seleccionar Billete de $500",
    instruction: "No calcules en tu mente. Toca el billete de $500 y el sistema te dirá exactamente cuánto cambio dar.",
    backendConsequence: "El sistema calcula el cambio real: $315.00 MXN ($500.00 - $185.00).",
    valueWhy: "Muestra el cambio correcto para entregar billetes grandes sin temor a equivocarse.",
  },
  {
    id: "m3_step7_confirm_500",
    moduleId: "module3_mistakes_noshow",
    moduleNumber: 3,
    moduleTitle: "Errores y Fantasmas",
    stepNumber: 7,
    totalSteps: 9,
    target: "confirm-demo-payment",
    action: "confirm",
    title: "7. Confirmar Pago Corregido",
    instruction: "Entrega los $315.00 de cambio y confirma el pago.",
    backendConsequence: "Registra la venta correcta en el libro contable ($555.00 MXN acumulados de práctica).",
    valueWhy: "La caja queda perfectamente cuadrada con el dinero físico.",
  },
  {
    id: "m3_step8_noshow_click",
    moduleId: "module3_mistakes_noshow",
    moduleNumber: 3,
    moduleTitle: "Errores y Fantasmas",
    stepNumber: 8,
    totalSteps: 9,
    target: "noshow-demo-order",
    action: "noshow-open",
    title: "8. Pedido Abandonado (No-Show)",
    instruction: "Un cliente nunca vino por su comida tras 20 minutos. Toca «Anular pedido / No-Show».",
    backendConsequence: "Abre el diálogo de anulación segura sin registrar cobro indebido ni descontar inventario dos veces.",
    valueWhy: "Limpia la pantalla de tickets zombis que confunden al equipo.",
    targetLane: "ready",
  },
  {
    id: "m3_step9_noshow_confirm",
    moduleId: "module3_mistakes_noshow",
    moduleNumber: 3,
    moduleTitle: "Errores y Fantasmas",
    stepNumber: 9,
    totalSteps: 9,
    target: "noshow-confirm",
    action: "noshow-confirm",
    title: "9. Confirmar Anulación No-Show",
    instruction: "Toca «Confirmar No-Show».",
    backendConsequence: "El pedido se quita de la fila y se archiva como No-Show con $0 MXN en ventas.",
    valueWhy: "Protege la caja de registrar ventas falsas y audita mermas reales.",
  },

  // --- MÓDULO 4: PÁNICO Y AGOTADOS ---
  {
    id: "m4_step1_inventory",
    moduleId: "module4_panic_86",
    moduleNumber: 4,
    moduleTitle: "Pánico y Agotados",
    stepNumber: 1,
    totalSteps: 5,
    target: "btn-inventory",
    action: "inventory-open",
    title: "1. Abrir Menú de Inventario",
    instruction: "¡Se acabó el Chicharrón! Toca el botón «Inventario» en la barra superior.",
    backendConsequence: "Abre el panel de control de disponibilidad de platillos y modificadores en vivo.",
    valueWhy: "Permite cortar inmediatamente la venta de productos agotados ('86') desde la estación de trabajo.",
  },
  {
    id: "m4_step2_toggle_86",
    moduleId: "module4_panic_86",
    moduleNumber: 4,
    moduleTitle: "Pánico y Agotados",
    stepNumber: 2,
    totalSteps: 5,
    target: "toggle-86-gordita",
    action: "toggle-stock",
    title: "2. Marcar Platillo como Agotado (86)",
    instruction: "Toca el interruptor de «Gordita de chicharrón» para marcarla como 'Agotado'.",
    backendConsequence: "El platillo se deshabilita instantáneamente en los teléfonos de los clientes; nadie podrá agregarlo al carrito.",
    valueWhy: "Evita que los clientes paguen por comida que la cocina no tiene ingredientes para preparar.",
  },
  {
    id: "m4_step3_close_inv",
    moduleId: "module4_panic_86",
    moduleNumber: 4,
    moduleTitle: "Pánico y Agotados",
    stepNumber: 3,
    totalSteps: 5,
    target: "close-inventory",
    action: "inventory-close",
    title: "3. Cerrar Inventario",
    instruction: "Toca la «X» para volver a la pantalla de comandas.",
    backendConsequence: "Guarda la configuración y regresa a la fila de pedidos.",
    valueWhy: "Flujo rápido sin abandonar la comanda activa.",
  },
  {
    id: "m4_step4_panic_pause",
    moduleId: "module4_panic_86",
    moduleNumber: 4,
    moduleTitle: "Pánico y Agotados",
    stepNumber: 4,
    totalSteps: 5,
    target: "btn-panic-pause",
    action: "panic-pause",
    title: "4. Botón de Pánico: Pausar Pedidos Web",
    instruction: "Llegó una multitud al restaurante. Toca «Pausar pedidos web» para detener los pedidos en línea.",
    backendConsequence: "Bloquea temporalmente nuevos pedidos móviles; los comensales ven 'Restaurante con alta demanda, pedidos web pausados'.",
    valueWhy: "Le da un respiro a la cocina para ponerse al día sin cancelar a los clientes que ya están sentados en el local.",
  },
  {
    id: "m4_step5_panic_resume",
    moduleId: "module4_panic_86",
    moduleNumber: 4,
    moduleTitle: "Pánico y Agotados",
    stepNumber: 5,
    totalSteps: 5,
    target: "btn-panic-resume",
    action: "panic-resume",
    title: "5. Reanudar Pedidos Web",
    instruction: "La cocina ya avanzó las órdenes pendientes. Toca «Reanudar pedidos web».",
    backendConsequence: "Reabre la tienda virtual y permite recibir nuevos pedidos en línea de inmediato.",
    valueWhy: "Control total del flujo de ventas sin reiniciar el sistema ni llamar al soporte técnico.",
  },

  // --- MÓDULO 5: GANANCIAS Y CIERRE ---
  {
    id: "m5_step1_nav_analytics",
    moduleId: "module5_revenue_closeout",
    moduleNumber: 5,
    moduleTitle: "Ganancias y Cierre",
    stepNumber: 1,
    totalSteps: 5,
    target: "btn-nav-analytics",
    action: "nav-analytics",
    title: "1. Auditar Caja y Ventas",
    instruction: "El turno ha terminado. Toca la pestaña «Caja y ventas» para ver el arqueo de tu práctica.",
    backendConsequence: "Muestra el estado financiero consolidado del turno con los pedidos de práctica realizados.",
    valueWhy: "Comprobar que cada peso cobrado coincide exactamente con los billetes en caja.",
  },
  {
    id: "m5_step2_inspect_revenue",
    moduleId: "module5_revenue_closeout",
    moduleNumber: 5,
    moduleTitle: "Ganancias y Cierre",
    stepNumber: 2,
    totalSteps: 5,
    target: "card-revenue-display",
    action: "inspect-revenue",
    title: "2. Verificar Ingresos Cobrados",
    instruction: "Aquí ves tus ganancias reales. El sistema ya sumó las órdenes de práctica. Toca 'Cerrar Turno' para hacer el corte de caja seguro.",
    backendConsequence: "Verifica que las 3 ventas de $185 suman $555.00, con $1,200.00 recibidos, $645.00 en cambio y 1 No-Show.",
    valueWhy: "Educación financiera: transparencia total del corte de caja sin fórmulas confusas.",
  },
  {
    id: "m5_step3_open_close_shift",
    moduleId: "module5_revenue_closeout",
    moduleNumber: 5,
    moduleTitle: "Ganancias y Cierre",
    stepNumber: 3,
    totalSteps: 5,
    target: "btn-close-shift",
    action: "close-shift-open",
    title: "3. Iniciar Cierre de Turno",
    instruction: "Toca «Cerrar Turno» para realizar el corte de caja seguro.",
    backendConsequence: "Abre el arqueo a ciegas (Blind Drop) donde debes registrar el efectivo físico.",
    valueWhy: "Garantiza un corte limpio para entregar el turno al siguiente taquero o cajero.",
  },
  {
    id: "m5_step4_blind_drop",
    moduleId: "module5_revenue_closeout",
    moduleNumber: 5,
    moduleTitle: "Ganancias y Cierre",
    stepNumber: 4,
    totalSteps: 5,
    target: "input-blind-drop",
    action: "blind-drop-input",
    title: "4. Arqueo de Caja a Ciegas",
    instruction: "Escribe la cantidad exacta de efectivo en caja: «555» o toca el botón «Cuadre Exacto: $555.00».",
    backendConsequence: "Comprueba matemáticamente que el cajero contó el dinero real sin discrepancias.",
    valueWhy: "Seguridad anti-fraude: previene declarar montos falsos al cerrar turno.",
  },
  {
    id: "m5_step5_confirm_close",
    moduleId: "module5_revenue_closeout",
    moduleNumber: 5,
    moduleTitle: "Ganancias y Cierre",
    stepNumber: 5,
    totalSteps: 5,
    target: "btn-confirm-close-shift",
    action: "close-shift-confirm",
    title: "5. Archivar y Cerrar Turno",
    instruction: "Toca «Archivar y cerrar» para sellar el turno de práctica.",
    backendConsequence: "Genera el recibo criptográfico de corte de turno y resetea el libro contable de prueba.",
    valueWhy: "Completaste el ciclo de vida completo de un turno en MasaFlow.",
  },
];
