import React,{createContext,useCallback,useContext,useEffect,useMemo,useRef,useState} from 'react';
import {decodeAnalytics,parseScope,queryScope,type AnalyticsDTO,type AnalyticsScope} from './analytics-contract';
import initialSnapshot from '../../data.json';
export type LiveState={dto:AnalyticsDTO|null;scope:AnalyticsScope;snapshot:any;loading:boolean;connected:boolean;error:string;refresh:()=>void;changeScope:(scope:Partial<AnalyticsScope>)=>void};
export const AnalyticsLiveContext=createContext<LiveState|null>(null);
export function useAnalyticsLive(){const value=useContext(AnalyticsLiveContext);if(!value)throw new Error('Live analytics provider missing');return value;}
const definitions:Record<string,any[]>={sales_summary:[{label:'Cash receipts / Cobros',definition:'Sum of verified cash payment totals including tax, grouped by paidAt. Tender, change, float and drops are excluded.',componentIds:['cash-receipts','sales-subtotal','paid-tickets','average-ticket','sales-summary-ai']},{label:'Average ticket / Ticket promedio',definition:'Verified cash receipts divided by paid ticket count; unavailable when there are no paid tickets.',componentIds:['average-ticket']}],sales_buckets:[{label:'Period receipts / Cobros del período',definition:'Verified receipt totals grouped into non-overlapping payment-time buckets in America/Mexico_City; cents are divided by 100 for chart display.',componentIds:['receipt-trend']}],menu_rank:[{label:'Units sold / Unidades',definition:'Item quantities from verified paid order snapshots; names and prices remain immutable.',componentIds:['top-dishes']}],receipts:[{label:'Verified receipts / Tickets verificados',definition:'Cash payments with matching order ID, paid record, amount, currency and valid payment timestamp.',componentIds:['recent-tickets']}],operations_summary:[{label:'Paid to pickup / Pago a entrega',definition:'Median completedAt minus paidAt for verified tickets completed today in America/Mexico_City; displays sample count.',componentIds:['pickup-time']},{label:'Active tickets / Tickets activos',definition:'All verified paid orders currently pending, preparing or ready, irrespective of sales period.',componentIds:['kitchen-count','oldest-ticket']}],active_queue:[{label:'Paid queue / Cola pagada',definition:'All active orders linked to verified cash receipts. Age is elapsed minutes since payment.',componentIds:['active-tickets']}],drawer_reconciliation:[{label:'Expected drawer / Caja esperada',definition:'Opening float plus verified shift cash receipts minus recorded cash drops; tender minus change equals receipts.',componentIds:['expected-cash','shift-drawer']}],drawer_audit:[{label:'Drawer variance / Diferencia de caja',definition:'Frozen physical count minus frozen expected amount for each closed shift; signed shortages are not netted against overages.',componentIds:['closed-audit']}]};
function localizedDefinitions(dto:AnalyticsDTO,id:string){
 const map:Record<string,string[]>={sales_summary:['cash_receipts','net_sales','tax_collected','ticket_count','average_ticket'],sales_buckets:['cash_receipts'],receipts:['cash_receipts'],operations_summary:['pickup_minutes','active_tickets'],active_queue:['active_tickets'],drawer_reconciliation:['expected_cash'],drawer_audit:['drawer_variance']};
 const metrics=Array.isArray(dto.metricDefinitions)?dto.metricDefinitions:[];
 const selected=(map[id]||[]).map(key=>metrics.find((row:any)=>row.id===key)).filter(Boolean).map((row:any)=>({...row,componentIds:definitions[id].flatMap(d=>d.componentIds)}));
 if(selected.length)return selected;
 return definitions[id].map(def=>({...def,label:dto.scope.lang==='es'?def.label.split(' / ')[1]||def.label:def.label.split(' / ')[0],definition:dto.scope.lang==='es'&&id==='menu_rank'?'Suma de cantidades en líneas de tickets con pago verificado; conserva nombres y precios originales.':def.definition}));
}
export function evidenceSnapshot(dto:AnalyticsDTO){const rows:Record<string,any[]>={sales_summary:[{...dto.sales,buckets:undefined,topItems:undefined,recentReceipts:undefined,currency:dto.currency}],sales_buckets:dto.sales.buckets.map(row=>({...row,amount:row.receiptsCents/100,currency:dto.currency})),menu_rank:dto.sales.topItems,receipts:dto.sales.recentReceipts,operations_summary:[{activeCount:dto.operations.activeCount,oldestAgeMinutes:dto.operations.oldestAgeMinutes,medianPickupMinutes:dto.operations.medianPickupMinutes,completedSampleCount:dto.operations.completedSampleCount,...dto.operations.counts}],active_queue:dto.operations.activeOrders,drawer_reconciliation:dto.operations.currentShift?[dto.operations.currentShift]:[],drawer_audit:dto.operations.latestAudit?[dto.operations.latestAudit]:[]};return {...initialSnapshot,buildStatus:'complete',status:'reviewed',generatedAt:dto.observedAt,_masaLive:true,_masaDto:dto,_masaView:{period:dto.scope.period,date:dto.scope.date,lang:dto.scope.lang},queries:Object.fromEntries(Object.entries(rows).map(([id,rows])=>[id,{rows,source:{label:'MasaFlow · Punto de venta / Point of sale',provider:'MasaFlow local API',executedAt:dto.observedAt,files:['.masaflow/state.json'],filters:[`tab=${dto.scope.tab}; period=${dto.scope.period}; date=${dto.scope.date}; currency=${dto.currency}; timezone=${dto.timezone}`,id.startsWith('sales')||id==='menu_rank'||id==='receipts'?`${dto.scope.startDate||dto.scope.date} – ${dto.scope.endDate||dto.scope.date}`:'Current operational state; independent of the sales date filter'],metricDefinitions:localizedDefinitions(dto,id),evidenceFlow:[{title:'Local cash ledger',detail:`GET /api/analytics?${queryScope(dto.scope)} · revision ${dto.revision}`},{title:'Receipt validation and aggregation',detail:'The server verifies payment/order links, paid amounts, currency snapshots and timestamps before grouping integer cents.'},...(Array.isArray(dto.evidenceFlow)?dto.evidenceFlow:[])],caveats:dto.scope.lang==='es'?[`Cobros inconsistentes excluidos: ${dto.quality.excludedReceipts}.`,`Cada fila conserva su moneda. No se convierten ni se suman monedas.`,`Fechas de entrega inválidas: ${dto.quality.invalidCompletionTimes||0}. Auditorías inválidas: ${dto.quality.invalidAudits||0}.`]:[`Excluded inconsistent receipts: ${dto.quality.excludedReceipts}.`,`Each financial row retains its currency; currencies are never converted or added.`,`Invalid completion timestamps: ${dto.quality.invalidCompletionTimes||0}. Invalid audits: ${dto.quality.invalidAudits||0}.`]}}]))};}
export function LiveAnalyticsProvider({children}:{children:(state:LiveState)=>React.ReactNode}){
 // Restore legacy links before the shared shell reads its initial tab.
 const [scope,setScope]=useState<AnalyticsScope>(()=>{const restored=parseScope(location.href);const url=new URL(location.href);url.searchParams.set('tab',restored.tab);history.replaceState(history.state,'',url);return restored;});const [dto,setDto]=useState<AnalyticsDTO|null>(null);const [loading,setLoading]=useState(true);const [connected,setConnected]=useState(false);const [error,setError]=useState('');const [nonce,setNonce]=useState(0);const generation=useRef(0);const revision=useRef(-1);const dtoRef=useRef(dto);dtoRef.current=dto;
 const refresh=useCallback(()=>setNonce(n=>n+1),[]);
 const changeScope=useCallback((change:Partial<AnalyticsScope>)=>setScope(current=>{const next={...current,...change};return queryScope(next)===queryScope(current)?current:next;}),[]);
 useEffect(()=>{const pop=()=>setScope(parseScope(location.href));window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[]);
 useEffect(()=>{try{localStorage.setItem('masaflow.locale',scope.lang);}catch{}document.documentElement.lang=scope.lang;const url=new URL(location.href);url.searchParams.set('period',scope.period);url.searchParams.set('date',scope.date);url.searchParams.set('lang',scope.lang);if(url.searchParams.get('tab')!=='owner'&&url.searchParams.get('tab')!=='operations')url.searchParams.set('tab',scope.tab);history.replaceState(history.state,'',url);},[scope]);
 useEffect(()=>{const events=new EventSource('/api/events');const updated=(event:MessageEvent)=>{try{const state=JSON.parse(event.data),incoming=state.revision;if(!Number.isSafeInteger(incoming)||incoming<0)return;if(incoming>revision.current){revision.current=incoming;refresh();}setConnected(true);}catch{/* Invalid event data never changes the revision watermark. */}};events.addEventListener('state',updated as EventListener);events.onmessage=updated;events.onopen=()=>{setConnected(true);refresh();};events.onerror=()=>{setConnected(false);setError(dtoRef.current?'Connection interrupted; showing the last confirmed data.':'Waiting for the local point of sale.');};const timer=setInterval(refresh,30000);return()=>{events.close();clearInterval(timer);};},[refresh]);
 useEffect(()=>{
   const id=++generation.current,controller=new AbortController();setLoading(true);
   async function load(){
     for(let attempt=0;attempt<3;attempt++){
       const response=await fetch('/api/analytics?'+queryScope(scope),{signal:controller.signal,cache:'no-store'});
       if(response.status===401){location.assign('/staff-login.html?next='+encodeURIComponent(location.pathname+location.search));throw new Error('Staff sign-in required.');}
       if(!response.ok)throw new Error('Analytics unavailable ('+response.status+')');
       const next=decodeAnalytics(await response.json());if(id!==generation.current)return;
       if(queryScope(next.scope)!==queryScope(scope))throw new Error('Analytics scope mismatch');
       if(next.revision<Math.max(revision.current,dtoRef.current?.revision??-1))continue;
       revision.current=Math.max(revision.current,next.revision);setDto(next);setError('');setLoading(false);return;
     }
     throw new Error('A newer ledger revision is available. Retrying preserves the last confirmed data.');
   }
   load().catch(failure=>{if(id!==generation.current||failure.name==='AbortError')return;setLoading(false);setError(failure.message);});return()=>controller.abort();
 },[scope,nonce]);
 const snapshot=useMemo(()=>dto?evidenceSnapshot(dto):{...initialSnapshot,_masaLive:true,buildStatus:'complete'},[dto]);const state={dto,scope,snapshot,loading,connected,error,refresh,changeScope};return <AnalyticsLiveContext.Provider value={state}>{children(state)}</AnalyticsLiveContext.Provider>;
}
